CREATE SEQUENCE SEQ_CONSUMO_ENERGIA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_CONSUMO_ENERGIA (
    CONSUMO_ENERGIA_ID INTEGER DEFAULT SEQ_CONSUMO_ENERGIA.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CONSUMO_HORA NUMBER(10, 2) NOT NULL,
    TEMPO_USO_MINUTOS NUMBER,
    CONSUMO_ENERGIA NUMBER(10, 2),
    DATA DATE,
    CONSTRAINT PK_CONSUMO_ENERGIA PRIMARY KEY (CONSUMO_ENERGIA_ID)
);